# Generated by Django 4.0 on 2022-01-04 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_joining',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
